### ISSUE TITLE
PlayChain can't create the database if the "PlayChain" folder is missing in Containers

### ISSUE THREAD

**Issue by iTaysonLab** [PlayCover/PlayTools#161]
Hello!

It seems that the new database-based PlayChain implementation fails to work when the "PlayChain" folder is not existing in `~/Library/Containers/PlayCover`. 

In Console, such messages can be found:
 ```
 os_unix.c:49333: (2) open(/Users/itaysonlab/Library/Containers/io.playcover.PlayCover/PlayChain/com.HoYoverse.Nap.db) - No such file or directory`
 PC-DEBUG: Failed to connect to DB
 PC-DEBUG: Failed to write keychain file
 ```
 
 This leads to breaking login in Hoyoverse games (Genshin/HSR/ZZZ) with the "Invalid parameter" error. Tested on ZZZ (and release-version PlayCover 3.0.0), now it is available to sign in after creating the folder.
 
 Thanks!

**Comment by TheMoonThatRises** [comment]
Hey! Did you launch ZZZ through the alias app or through PlayCover? If you launched it directly from the app, try launching it from PlayCover as I think the PlayChain db file is created through the PlayCover app.

**Comment by iTaysonLab** [comment]
> If you launched it directly from the app

Well, I always double-tapped the icon from the PlayCover application, without using the alias in Launchpad. I also trying clearing PlayChain for ZZZ and enabling/disabling it - still didn't help. Only manually creating the directory fixed it.

**Comment by ash-development** [comment]
Can confirm this happens with Genshin - was getting `Parameter error` prior to making the PlayChain folder myself
