### ISSUE TITLE
Does PlayTools support the IOS13-SimulateTouch function?

### ISSUE THREAD

**Issue by CrazyEig** [PlayCover/PlayTools#164]
I found that PlayTools implements touch functionality based on PTFakeTouch (https://github.com/Ret70/PTFakeTouch), which in turn is based on iOS13-SimulateTouch (https://github.com/xuan32546/IOS13-SimulateTouch). iOS13-SimulateTouch has some very interesting features, such as:

Color picker: Get the color of a specified pixel.
Image matching.
OCR.
Remote controlling.
I want to use Python programming to automate games, so these features are very useful. Does PlayTools support these functionalities? If not, are there any plans to support them in the future? Thank you.

**Comment by JoseMoreville** [comment]
We do not support any kind of macro or tooling that enables bots or cheating in games.
