### ISSUE TITLE
Skills swap/drag

### ISSUE THREAD

**Issue by WRedMedia** [PlayCover/PlayTools#167]
Is there a way to swap skills with a single button press, like using the spacebar, instead of combining it with mouse movement? (see gif bellow)
![skill-swap](https://github.com/user-attachments/assets/394b1375-443b-4a36-9812-96536c7a6b47)

**Comment by JoseMoreville** [comment]
Please refer to: [https://docs.playcover.io/keymapping/using_making_keymaps](url) I remember this feature was implemented over a year ago 

https://github.com/PlayCover/PlayTools/pull/24](https://github.com/PlayCover/PlayTools/pull/24
