### ISSUE TITLE
Keymapping - No directional arrows option(Infinity Nikki)

### ISSUE THREAD

**Issue by Brightstraw** [PlayCover/PlayTools#175]
Hi all, 
As seen in the image below, when I open keymapping editor there's no option to select directional arrows on my macbook M1 (game - Infinity Nikki). If possible, has anyone else come across this issue and knows how to resolve it? Thanks alot!

![image](https://github.com/user-attachments/assets/301cc996-7f8c-4a00-9c57-bd63d01507f5)

**Comment by TheMoonThatRises** [comment]
Duplicate issue of https://github.com/PlayCover/PlayCover/issues/1771.
