### ISSUE TITLE
v2.0.2 may introduced some bug which causes game FPS reduced drastically

### ISSUE THREAD

**Issue by macvip** [PlayCover/PlayTools#58]
Origin issue https://github.com/PlayCover/PlayCover/issues/573
Comparing PlayCover's build log of [Build nightly release #168](https://github.com/PlayCover/PlayCover/actions/runs/3632859628/jobs/6129188820) to [Build nightly release #167](https://github.com/PlayCover/PlayCover/actions/runs/3623389434/jobs/6109194792), PlayTools ["v2.0.2"](https://github.com/PlayCover/PlayTools/commit/2a5a5053f771437fe649a556aca0cc46c6d1287e) is checked out and linked  in the newer versions of PlayCover (while PlayTools ["v2.0.1"](https://github.com/PlayCover/PlayTools/commit/320d5f3dbf85cca1ae46e4aa6fb102fec50a8a19) in the older).
I downloaded the newest PlayCover:develop source code, modified [Cartfile](https://github.com/PlayCover/PlayCover/blob/develop/Cartfile) to require exactly version 2.0.1 of PlayTools, then compiled PlayCover.app locally. The PlayCover.app worked as well as "nightly release #167".
If the newest PlayCover:develop source code was compiled directly and it required version 2.0.2 of PlayTools, the PlayCover.app worked the same as "nightly release #167", resulting FPS reduced.
@IsaacMarovitz , would you please take a look at that problem? Thanks a lot.

**Comment by TheMoonThatRises** [comment]
Can you try running PlayCover with https://github.com/PlayCover/PlayTools/pull/57 as PlayTools? It may help fix the problem.
