### ISSUE TITLE
[Bug]: anomalous Mouse Button behavior

### ISSUE THREAD

**Issue by FlyMeToTheMoonAndLetMePlayAmongTheStars** [PlayCover/PlayTools#62]
### Describe the bug

[See for yourself](https://files.catbox.moe/r3ettx.mov) 

When choosing the circle mouse button, it works as expected. You can create an 'empty' mouse circle to control the camera movements. When you select the circle mouse button and press a key, you can bind it to a key to create a button that lets you drag the camera around when the button is held. 

On the other hand, when you create a rounded square mouse button, you can also use it to control the camera movement, but if you try to bind this button to any key, it will somehow create a WASD directional button

I'm pretty sure this is a bug and not a feature. And that the rounded square mouse button is supposed to behave the same or similar as the circle one.

### Steps to reproduce

1. Open Keymap Editor
2. Create a rounded square mouse button
3. Select this button 
4. Press any key and it will turn the button into a directional pad 

### Expected behaviour

Same behavior as the circle mouse button i think?

### Crash log

```shell
no crash
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment]
Square mouse area is meant to be used as movement control not camera control. for example in games like wild rift you cannot control movement with wasd and also you have no camera to control so you use square mouse area.
the difference is square mouse area does not automatically cut input like the circle one that after some seconds cuts input off to act like right thumb stick of a controller

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
then shouldn't it NOT turn into a WASD pad when you press any key while its selected? considering there's already another button that lets you add the WASD pad directly

**Comment by amirsaam** [comment]
this behaviour tries to make user avoid doing such thing and shows that this controller is meant to be movement control, however i do agree to not letting user assign any button can be better approach.
