### ISSUE TITLE
keymapping unusual behaviour

### ISSUE THREAD

**Issue by Juhao73692** [PlayCover/PlayTools#97]
when I press opt, the key mapping can't work properly. I then try cmd+K to edit key mapping but can't close the editing page with cmd+K. then I try to close key mapping editing with the top bar and after that I can't find my mouse and can only click the mouse button.

**Comment by XuYicong** [comment]
Should have been fixed by #83. Try a recent nightly version and see if it got fixed.

**Comment by Juhao73692** [comment]
> 

I am using playcover2.0.4 and playtools2.0.7

**Comment by XuYicong** [comment]
https://github.com/PlayCover/PlayCover/actions/runs/4300040261 Try this

**Comment by Juhao73692** [comment]
Thanks I’ll try later

**Comment by Juhao73692** [comment]
solved
